### ISSUE TITLE
error: no member named 'rand' in '/usr/lib/zig/std/index.zig'

### ISSUE THREAD

**Issue by xyproto** [andrewrk/tetris#1]
Hi,

I'm using zig version 0.0.0 on 64-bit Arch Linux.

```
$ zig version
0.0.0
```

When building tetris, I get the following error:

```
$ zig build src/main.zig --name tetris --export exe --library c --library m --library glfw --library epoxy --library png --library z            
src/main.zig:2:17: error: no member named 'rand' in '/usr/lib/zig/std/index.zig'
const Rand = std.rand.Rand;
```

Best regards,
Alexander F Rødseth

**Comment by andrewrk** [comment]
Pull zig master branch and rebuild. I updated both projects at the same time.

**Comment by xyproto** [comment]
With the latest master branch (stil 0.0.0) I get this error instead:

```
% zig build src/main.zig --name tetris --export exe --library c --library m --library glfw --library epoxy --library png --library z
Unable to determine libc lib path.
zsh: abort (core dumped)  zig build src/main.zig --name tetris --export exe --library c --library m    
134...ckout/zigtris% 
```

**Comment by andrewrk** [comment]
You're closer to having it working now. What's going on here is that Zig doesn't know where libc is on your system, which is something that you have to inform Zig of either at configure time with configure options, or at compile time with compile flags.

The argument that sets the libc lib path is `ZIG_LIBC_LIB_DIR`. In the Zig readme it suggests using `$(dirname $(cc -print-file-name=crt1.o))` to find out what directory that is on your system. If this heuristic fails, it's up to you to figure out what directory to supply instead.

I suggest, after building zig, running the test suite with `./run_tests`. This will ensure that your build is configured properly and once that passes, then tetris will build fine too.

**Comment by xyproto** [comment]
Used the OS X instructions for adding defines for CMake and updated [the zig package](https://aur.archlinux.org/packages/zig/). Tetris compiles and runs now. :+1:
