### ISSUE TITLE
`error: use of undeclared identifier '_'` with zig 0.4.0

### ISSUE THREAD

**Issue by phtrivier** [andrewrk/tetris#26]
I just grabbed the 0.4.0 version of the linux compiler: 

```
± |master ✓| → ~/apps/zig-linux-x86_64-0.4.0/zig version
0.4.0
```

When trying to build the `master` branch following the `README.md`, I get this error: 

```
/home/phtrivier/perso/src/zig/tetris/build.zig:9:60: error: use of undeclared identifier '_'
    exe.addCSourceFile("stb_image-2.22/stb_image_impl.c", [_][]const u8{"-std=c99"});
                                                           ^


```

Am I missing something, or should I use a "master" version of the compiler ?

**Comment by sacredbirdman** [comment]
Gives me the same error with 0.4.0 but works with the git version of the compiler. Maybe the build file could include required compiler version to mitigate problems like this?
