### ISSUE TITLE
error: container 'builtin' has no member called 'Environ'

### ISSUE THREAD

**Issue by markfirmware** [andrewrk/tetris#3]
I would like to refactor to separate the game logic from io in order to add ultibo as a replacement for glfw. Would you be amenable to pull requests for that kind of refactoring?

The first step is to start with a working build:

debian 9 x86/64:
```
root@localhost:~/github.com/andrewrk/tetris# zig build
/root/github.com/andrewrk/tetris/build.zig:12:71: error: container 'builtin' has no member called 'Environ'
        exe.setTarget(builtin.Arch.x86_64, builtin.Os.windows, builtin.Environ.gnu);
                                                                      ^
root@localhost:~/github.com/andrewrk/tetris# zig version
0.3.0+5469e3e3
```

**Comment by andrewrk** [comment]
I fixed the build script, but now getting this:

```
[nix-shell:~/dev/tetris]$ zig build play
/home/andy/dev/tetris/src/c.zig:1:9: error: C import failed
pub use @cImport({
        ^
/home/andy/dev/zig/build/lib/zig/libc/include/generic-glibc/bits/local_lim.h:38:10: note: 'linux/limits.h' file not found
#include <linux/limits.h>
         ^

```

I know how to fix it. It is a missing header we need to grab from linux.

**Comment by andrewrk** [comment]
Fixed in https://github.com/ziglang/zig/commit/8369ddb09c6fb4ae86d04a8e838c7be42bc22097

**Comment by andrewrk** [comment]
To answer your question, I think it would be a fun project to do that, and I am amenable to such pull requests, if you will allow me to later change my mind and request that we continue the effort in a new repository so that this one can go back to being a dead simple example.

**Comment by markfirmware** [comment]
Sounds great. I’ll stay out of the way until you get 0.4 out the door.
