### ISSUE TITLE
Refactoring discussion

### ISSUE THREAD

**Issue by markfirmware** [andrewrk/tetris#4]
Design constraints:
* simplicity

**Comment by markfirmware** [comment]
Replace printf with std.debug.warn?

**Comment by andrewrk** [comment]
> Replace printf with std.debug.warn?

Sounds good. The original tetris codebase predates even `std.debug.warn` :-)

**Comment by markfirmware** [comment]
Please see https://github.com/markfirmware/tetris/issues/1

**Comment by markfirmware** [comment]
Putting ultibo aside for a couple of days - getting ncurses working first - https://github.com/markfirmware/tetris/issues/9
