### ISSUE TITLE
Broken Youtube link in README and repo description

### ISSUE THREAD

**Issue by Atomk** [andrewrk/tetris#44]
It looks like the video is private or deleted.

**Comment by kassane** [comment]
correct link: https://vimeo.com/481429586

Andrew has been off youtube for some time. see: https://www.youtube.com/watch?v=qjz6xNO63mI

**Comment by andrewrk** [comment]
there's no link in the readme anymore

**Comment by Atomk** [comment]
It still is in the repo description though:
![image](https://github.com/andrewrk/tetris/assets/6122017/b6e08864-2d43-47c5-bd1c-7944550a77db)

**Comment by andrewrk** [comment]
aha, thank you. fixed
