### ISSUE TITLE
Unifying similar code for particles and falling blocks

### ISSUE THREAD

**Issue by markfirmware** [andrewrk/tetris#7]
https://github.com/andrewrk/tetris/blob/c2aa222f09cb218926a1b6925076667a253f62ca/src/main.zig#L400-L424

Lines 407 and 420 are similar - one uses framebuffer_height and one uses window_height - should they be the same? Also line 420 adds 10.0 - should that be margin_size:
https://github.com/andrewrk/tetris/blob/c2aa222f09cb218926a1b6925076667a253f62ca/src/main.zig#L68
and should it also be in line 407?

Regards, Mark

**Comment by andrewrk** [comment]
I think the framebuffer one is fine for both.

**Comment by markfirmware** [comment]
Thanks
